name: 'Try action'
on:
  push:
    branches:
      - develop

jobs:
  try_action:
    runs-on: ubuntu-20.04
    name: Try action
    steps:
      - uses: actions/checkout@v2
      - name: My action step
        uses: ./
        id: try-action
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          TARGET_REPOSITORY: 'Slime-hatena/sandbox'
      - name: Get the output time
        run: echo "The time was ${{ steps.try-action.outputs.time }}"
